<a href="https://colab.research.google.com/github/mohammad-nahid-hossain/MSc.-Projects-Part-2/blob/main/My_CI_Project_RF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/


In [ ]:
!ls "/content/drive/My Drive/"

 2014_Bodily_Maps_of_Emotions.mat
'2019110211_Hossain Mohammad Nahid.gdoc'
 Books
'Books(islamic)'
'Bsc Thesis'
 CERTIFICATES
'Colab Notebooks'
 Coursera
 CV
'Data Acquisition for research work'
 DeepLearningBook.pdf
'Dream forest tour'
'Getting started.pdf'
'GME transaction'
 Hmmmmm.gsheet
'How to install cuda 10.1 in Ubuntu 18.04.zip'
 IMG_4717.JPG
 IMG_4719.JPG
 lecture_1.pdf
 lecture_2.pdf
 lecture_3.pdf
 lecture_4.pdf
 Msc
 Neural-Network-based-finger-counting-technique.pdf
'New Doc 2019-09-03 20.05.57.jpg'
 Paper
'PhD Application'
'PhD Application Pack'
'Planning Document.docx'
'Planning Document.odt'
'Planning Document.pdf'
'Snow fall video'


In [ ]:
import numpy as np 
import pandas as pd 

In [ ]:
#Importing Dataset 
dataset = pd.read_csv('/content/drive/My Drive/Msc/Msc Thesis/Coding Documents/AFS/RF/My_Project_CI_data.csv') 

In [ ]:
dataset.head()

TotalTime       AVG      Energy  Step  Group
0         12  1.500000  302.500000   605      3
1         13  2.166667  183.333333   550      3
2         10  1.428571  183.333333   550      3
3         12  1.500000  183.333333   550      3
4         10  1.250000  201.666667   605      3

In [ ]:
# Preparing Data For Training 
X = dataset.iloc[:, 0:4].values
y = dataset.iloc[:, 4].values

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [ ]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test) 

In [ ]:
# Training the Algorithm
from sklearn.ensemble import RandomForestClassifier

regressor = RandomForestClassifier(n_estimators=20, random_state=0)
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)

In [ ]:
# Evaluating the Algorithm
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[674  58  33   6]
 [ 84  65   7  20]
 [ 60  23   6   6]
 [  6  20   1  26]]
              precision    recall  f1-score   support

           0       0.82      0.87      0.85       771
           1       0.39      0.37      0.38       176
           2       0.13      0.06      0.08        95
           3       0.45      0.49      0.47        53

    accuracy                           0.70      1095
   macro avg       0.45      0.45      0.44      1095
weighted avg       0.67      0.70      0.69      1095

0.7041095890410959
