<a href="https://colab.research.google.com/github/mohammad-nahid-hossain/MSc.-Projects-Part-2/blob/main/My_CI_Project_SVM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/


In [ ]:
!ls "/content/drive/My Drive/"

 2014_Bodily_Maps_of_Emotions.mat
'2019110211_Hossain Mohammad Nahid.gdoc'
 Books
'Books(islamic)'
'Bsc Thesis'
 CERTIFICATES
'Colab Notebooks'
 Coursera
 CV
'Data Acquisition for research work'
 DeepLearningBook.pdf
'Dream forest tour'
'Getting started.pdf'
'GME transaction'
 Hmmmmm.gsheet
'How to install cuda 10.1 in Ubuntu 18.04.zip'
 IMG_4717.JPG
 IMG_4719.JPG
 lecture_1.pdf
 lecture_2.pdf
 lecture_3.pdf
 lecture_4.pdf
 Msc
 Neural-Network-based-finger-counting-technique.pdf
'New Doc 2019-09-03 20.05.57.jpg'
 Paper
'PhD Application'
'PhD Application Pack'
'Planning Document.docx'
'Planning Document.odt'
'Planning Document.pdf'
'Snow fall video'


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
CI_data = pd.read_csv("/content/drive/My Drive/Msc/Msc Thesis/Coding Documents/AFS/SVM/My_Project_CI_data.csv")

In [ ]:
CI_data.shape

(5475, 5)

In [ ]:
CI_data.head()

TotalTime       AVG      Energy  Step  Group
0         12  1.500000  302.500000   605      3
1         13  2.166667  183.333333   550      3
2         10  1.428571  183.333333   550      3
3         12  1.500000  183.333333   550      3
4         10  1.250000  201.666667   605      3

In [ ]:
X = CI_data.drop('Group', axis=1)
y = CI_data['Group']

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30)

In [ ]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='linear')
svclassifier.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
y_pred = svclassifier.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import accuracy_score 
print(confusion_matrix(y_test,y_pred))
print ("Accuracy : ", accuracy_score(y_test,y_pred)*100) 
print(classification_report(y_test,y_pred))

[[1134   41    0    0]
 [ 203   72    0    0]
 [ 103   12    0    0]
 [  25   53    0    0]]
Accuracy :  73.40231284236154
              precision    recall  f1-score   support

           0       0.77      0.97      0.86      1175
           1       0.40      0.26      0.32       275
           2       0.00      0.00      0.00       115
           3       0.00      0.00      0.00        78

    accuracy                           0.73      1643
   macro avg       0.29      0.31      0.29      1643
weighted avg       0.62      0.73      0.67      1643



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
